name: Deploy to AKS
on:
  push:
    branches: feat/3-tier-app

env:
  AKS_CLUSTER_NAME: your-cluster
  AKS_RESOURCE_GROUP: your-resource-group
  DOCKER_HUB_USERNAME: yourdockerhubusername  # Add your Docker Hub username

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ env.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} ./application/frontend
        docker push ${{ env.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }}
        # Also tag as latest
        docker tag ${{ env.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} ${{ env.DOCKER_HUB_USERNAME }}/frontend:latest
        docker push ${{ env.DOCKER_HUB_USERNAME }}/frontend:latest

    - name: Build and push backend image
      run: |
        docker build -t ${{ env.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }} ./application/backend
        docker push ${{ env.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }}
        # Also tag as latest
        docker tag ${{ env.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }} ${{ env.DOCKER_HUB_USERNAME }}/backend:latest
        docker push ${{ env.DOCKER_HUB_USERNAME }}/backend:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Package Helm Chart
      run: |
        helm package ./helm
        echo "HELM_PACKAGE=$(ls three-tier-app-*.tgz)" >> $GITHUB_ENV

    - name: Get Ingress IP
      run: |
        EXTERNAL_IP=$(kubectl get service -n ingress-nginx nginx-ingress-ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV

    - name: Deploy to AKS
      run: |
        helm upgrade --install three-tier-app ${{ env.HELM_PACKAGE }} \
          --set frontend.image.repository=${{ env.DOCKER_HUB_USERNAME }}/frontend \
          --set frontend.image.tag=${{ github.sha }} \
          --set backend.image.repository=${{ env.DOCKER_HUB_USERNAME }}/backend \
          --set backend.image.tag=${{ github.sha }} \
          --set ingress.serviceIP=${{ env.EXTERNAL_IP }}
