apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  REACT_APP_BACKEND_URL: "http://{{ .Values.ingress.serviceIP }}/api"  # Will be replaced with actual IP
  DB_HOST: "{{ .Release.Name }}-database"
  DB_PORT: "5432"
  DB_NAME: "itemsdb"