# Ingress Configuration
ingress:
  enabled: true
  serviceIP: "" # Will be set during deployment

# Frontend Configuration
frontend:
  name: frontend
  image:
    repository: gauravrai3366/frontend
    tag: 1.0.0
    pullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

# Backend Configuration
backend:
  name: backend
  image:
    repository: gauravrai3366/backend  
    tag: 1.0.0
    pullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

# Database Configuration
database:
  name: postgres
  image:
    repository: postgres
    tag: 13-alpine
    pullPolicy: IfNotPresent
  username: admin       # Single username definition
  password: test       # Single password definition
  dbname: itemsdb     
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

# Network Policies
networkPolicy:
  enabled: true

# Autoscaling Configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80